# Generated by Django 3.1.5 on 2021-01-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiry',
            new_name='Contact',
        ),
    ]
